apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: java-libray
  description: An example java backstage application.
  annotations:
     backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
